#!/bin/sh

# SPDX-License-Identifier: MIT-0
# 2026 Charles Terrell
#
# dstamp
#
# Rename files using today's date as YYYYMMDD.
#
# Example: If today is 30 Sept 2026,
#   dstamp notes.md
# renames notes.md to 20260930-notes.md
#
# It does this for every file listed in the args.
# Stamping other dates (past, future, modified...)
# could be added easily if needed.

# set -x
DATE=$(date +%Y%m%d)
for file in "$@"; do
    if [ -f "$file" ]; then
        mv "$file" "$DATE-$file"
    fi
done
