#!/bin/sh

# SPDX-License-Identifier: MIT-0
# 2026 Charles Terrell
#
# Cross-distro system update command that avoids having
# to remember which commands apply to this particular
# machine. Also saves typing when more than one package
# manager exists. Can be symlinked to whatever name you
# want to simplify tab completion.

CMD_NAME="${0##*/}"

echo "-- $CMD_NAME start"

if command -v apt-get >/dev/null 2>&1; then
    echo "-- apt-get found"
    sudo apt-get update
    sudo apt-get upgrade
fi

if command -v dnf >/dev/null 2>&1; then
    echo "-- dnf found"
    sudo dnf update
fi

if command -v snap >/dev/null 2>&1; then
    echo "-- snap found"
    sudo snap refresh
fi

if command -v flatpak >/dev/null 2>&1; then
    echo "-- flatpack found"
    flatpak update
fi

echo "-- $CMD_NAME done"

# the original way on a former fedora machine
# konsole --hold -e "flatpak update ; exec /bin/bash" &
# sudo dnf update
